clearml-project-config:
  project-name: Take Home Test Model-eFishery
  task-name: Vibrio Detection and Counting
  id: 571627334eeb4e4aacfbeb177f38d97b
  task-type: inference

model-config:
  YOLO-model: Vibrio-eFishery
  published: True
  tags: []
  delimiter: delimiter/delimiter6.png
  vision-key: development-356407-6002a5991254.json
  image-size: 640
  device-mode: cpu
  save-mode: False
  conf: 0.25
  iou: 0.25
